services:
    web:
        container_name: tanart-web-service
        image: tanart-virtual-gallery:lighter
        # build:
        #     dockerfile: Dockerfile
        #     context: .
        ports:
            - 3001:3000
        env_file:
            - .env
        volumes:
            - ./public:/app/public
