services:
    web:
        container_name: tanart-web-service
        image: luthfi9251/tanart-virtual-gallery:light-latest
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 3000:3000
        env_file:
            - .env
        environment:
            - DATABASE_URL=mysql://root:root@localhost:3306/tanart-virtual-gallery?schema=public
