services:
    web:
        container_name: tanart-web-service
        image: tanart-virtual-gallery:lighter
        # build:
        #     dockerfile: Dockerfile
        #     context: .
        ports:
            - 3000:3000
        env_file:
            - .env
        environment:
            - DATABASE_URL=mysql://root:B4rc3lon4@host.docker.internal:3306/tanart-virtual-gallery?schema=public
        volumes:
            - ./public:/app/public
