import { Inter } from "next/font/google";
import { Notifications } from "@mantine/notifications";
import QueryProvider from "./QueryProvider";
import "./globals.css";

import { createTheme, MantineProvider, ColorSchemeScript } from "@mantine/core";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const myColor = [
    "#ebfcff",
    "#d7f7fc",
    "#aaeffb",
    "#7ce7fa",
    "#60e0f8",
    "#53dcf8",
    "#4bdaf9",
    "#3ec1de",
    "#2eacc6",
    "#00849A",
];

const theme = createTheme({
    colors: {
        myColor,
    },
});

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={inter.className}>
                <QueryProvider>
                    <MantineProvider theme={theme} defaultColorScheme="light">
                        <Notifications />
                        {children}
                    </MantineProvider>
                </QueryProvider>
            </body>
        </html>
    );
}
