import { createTheme, MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Poppins } from "next/font/google";
import AppLayoutProvider from "../AppLayoutProvider";
import "../globals.css";
import Navbar from "./Navbar";
import { auth } from "@/auth";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
    title: "TanArt Virtual Gallery",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await auth();

    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={poppins.className}>
                <AppLayoutProvider>
                    <Navbar session={session}>{children}</Navbar>
                </AppLayoutProvider>
            </body>
        </html>
    );
}
