import { createTheme, MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Poppins } from "next/font/google";
import AppLayoutProvider from "../AppLayoutProvider";
import "../globals.css";
import Navbar from "./Navbar";
import { auth } from "@/auth";
import withAuthAndRoleCheck from "@/hoc/withAuthAndRoleCheck";
import { PAGE_CONFIG } from "@/variables/page";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
    title: "TanArt Virtual Gallery",
    description: "Generated by create next app",
};

async function RootLayout(props) {
    console.log({ props });
    const session = props.session;
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={poppins.className}>
                <AppLayoutProvider>
                    <Navbar session={session}>{props.children}</Navbar>
                </AppLayoutProvider>
            </body>
        </html>
    );
}

export default withAuthAndRoleCheck(
    RootLayout,
    PAGE_CONFIG.KURATOR_DASHBOARD.name
);
